# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\"\x19\n\tChannelID\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0c\x43hannelViews\x12\r\n\x05views\x18\x01 \x01(\x04\x32,\n\x05Views\x12#\n\x04view\x12\n.ChannelID\x1a\r.ChannelViews\"\x00\x62\x06proto3'
)




_CHANNELID = _descriptor.Descriptor(
  name='ChannelID',
  full_name='ChannelID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ChannelID.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=41,
)


_CHANNELVIEWS = _descriptor.Descriptor(
  name='ChannelViews',
  full_name='ChannelViews',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='views', full_name='ChannelViews.views', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['ChannelID'] = _CHANNELID
DESCRIPTOR.message_types_by_name['ChannelViews'] = _CHANNELVIEWS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChannelID = _reflection.GeneratedProtocolMessageType('ChannelID', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELID,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ChannelID)
  })
_sym_db.RegisterMessage(ChannelID)

ChannelViews = _reflection.GeneratedProtocolMessageType('ChannelViews', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELVIEWS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ChannelViews)
  })
_sym_db.RegisterMessage(ChannelViews)



_VIEWS = _descriptor.ServiceDescriptor(
  name='Views',
  full_name='Views',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='view',
    full_name='Views.view',
    index=0,
    containing_service=None,
    input_type=_CHANNELID,
    output_type=_CHANNELVIEWS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIEWS)

DESCRIPTOR.services_by_name['Views'] = _VIEWS

# @@protoc_insertion_point(module_scope)
